# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/product.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Protos/product.proto\x12\x07Product\"9\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1e\n\x10ProductIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"G\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\t\x12\x0b\n\x03msg\x18\x04 \x01(\t2\x9e\x02\n\x0eProductService\x12?\n\nAddProduct\x12\x17.Product.ProductRequest\x1a\x18.Product.ProductResponse\x12\x41\n\nGetProduct\x12\x19.Product.ProductIdRequest\x1a\x18.Product.ProductResponse\x12\x42\n\rUpdateProduct\x12\x17.Product.ProductRequest\x1a\x18.Product.ProductResponse\x12\x44\n\rDeleteProduct\x12\x19.Product.ProductIdRequest\x1a\x18.Product.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTREQUEST']._serialized_start=33
  _globals['_PRODUCTREQUEST']._serialized_end=90
  _globals['_PRODUCTIDREQUEST']._serialized_start=92
  _globals['_PRODUCTIDREQUEST']._serialized_end=122
  _globals['_PRODUCTRESPONSE']._serialized_start=124
  _globals['_PRODUCTRESPONSE']._serialized_end=195
  _globals['_PRODUCTSERVICE']._serialized_start=198
  _globals['_PRODUCTSERVICE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
