# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos import product_pb2 as Protos_dot_product__pb2


class ProductServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddProduct = channel.unary_unary(
                '/Product.ProductService/AddProduct',
                request_serializer=Protos_dot_product__pb2.ProductRequest.SerializeToString,
                response_deserializer=Protos_dot_product__pb2.ProductResponse.FromString,
                )
        self.GetProduct = channel.unary_unary(
                '/Product.ProductService/GetProduct',
                request_serializer=Protos_dot_product__pb2.ProductIdRequest.SerializeToString,
                response_deserializer=Protos_dot_product__pb2.ProductResponse.FromString,
                )
        self.UpdateProduct = channel.unary_unary(
                '/Product.ProductService/UpdateProduct',
                request_serializer=Protos_dot_product__pb2.ProductRequest.SerializeToString,
                response_deserializer=Protos_dot_product__pb2.ProductResponse.FromString,
                )
        self.DeleteProduct = channel.unary_unary(
                '/Product.ProductService/DeleteProduct',
                request_serializer=Protos_dot_product__pb2.ProductIdRequest.SerializeToString,
                response_deserializer=Protos_dot_product__pb2.ProductResponse.FromString,
                )


class ProductServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProduct,
                    request_deserializer=Protos_dot_product__pb2.ProductRequest.FromString,
                    response_serializer=Protos_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=Protos_dot_product__pb2.ProductIdRequest.FromString,
                    response_serializer=Protos_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=Protos_dot_product__pb2.ProductRequest.FromString,
                    response_serializer=Protos_dot_product__pb2.ProductResponse.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=Protos_dot_product__pb2.ProductIdRequest.FromString,
                    response_serializer=Protos_dot_product__pb2.ProductResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Product.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Product.ProductService/AddProduct',
            Protos_dot_product__pb2.ProductRequest.SerializeToString,
            Protos_dot_product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Product.ProductService/GetProduct',
            Protos_dot_product__pb2.ProductIdRequest.SerializeToString,
            Protos_dot_product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Product.ProductService/UpdateProduct',
            Protos_dot_product__pb2.ProductRequest.SerializeToString,
            Protos_dot_product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Product.ProductService/DeleteProduct',
            Protos_dot_product__pb2.ProductIdRequest.SerializeToString,
            Protos_dot_product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
