# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos import user_pb2 as Protos_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
            "/User.UserService/AddUser",
            request_serializer=Protos_dot_user__pb2.UserRequest.SerializeToString,
            response_deserializer=Protos_dot_user__pb2.UserResponse.FromString,
        )
        self.GetUser = channel.unary_unary(
            "/User.UserService/GetUser",
            request_serializer=Protos_dot_user__pb2.UserIdRequest.SerializeToString,
            response_deserializer=Protos_dot_user__pb2.UserResponse.FromString,
        )
        self.UpdateUser = channel.unary_unary(
            "/User.UserService/UpdateUser",
            request_serializer=Protos_dot_user__pb2.UserRequest.SerializeToString,
            response_deserializer=Protos_dot_user__pb2.UserResponse.FromString,
        )
        self.DeleteUser = channel.unary_unary(
            "/User.UserService/DeleteUser",
            request_serializer=Protos_dot_user__pb2.UserIdRequest.SerializeToString,
            response_deserializer=Protos_dot_user__pb2.UserResponse.FromString,
        )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddUser": grpc.unary_unary_rpc_method_handler(
            servicer.AddUser,
            request_deserializer=Protos_dot_user__pb2.UserRequest.FromString,
            response_serializer=Protos_dot_user__pb2.UserResponse.SerializeToString,
        ),
        "GetUser": grpc.unary_unary_rpc_method_handler(
            servicer.GetUser,
            request_deserializer=Protos_dot_user__pb2.UserIdRequest.FromString,
            response_serializer=Protos_dot_user__pb2.UserResponse.SerializeToString,
        ),
        "UpdateUser": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateUser,
            request_deserializer=Protos_dot_user__pb2.UserRequest.FromString,
            response_serializer=Protos_dot_user__pb2.UserResponse.SerializeToString,
        ),
        "DeleteUser": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteUser,
            request_deserializer=Protos_dot_user__pb2.UserIdRequest.FromString,
            response_serializer=Protos_dot_user__pb2.UserResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "User.UserService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/User.UserService/AddUser",
            Protos_dot_user__pb2.UserRequest.SerializeToString,
            Protos_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/User.UserService/GetUser",
            Protos_dot_user__pb2.UserIdRequest.SerializeToString,
            Protos_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/User.UserService/UpdateUser",
            Protos_dot_user__pb2.UserRequest.SerializeToString,
            Protos_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def DeleteUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/User.UserService/DeleteUser",
            Protos_dot_user__pb2.UserIdRequest.SerializeToString,
            Protos_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
