# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Protos/user.proto\x12\x04User\"6\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1b\n\rUserIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"D\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0b\n\x03msg\x18\x04 \x01(\t2\xdf\x01\n\x0bUserService\x12\x30\n\x07\x41\x64\x64User\x12\x11.User.UserRequest\x1a\x12.User.UserResponse\x12\x32\n\x07GetUser\x12\x13.User.UserIdRequest\x1a\x12.User.UserResponse\x12\x33\n\nUpdateUser\x12\x11.User.UserRequest\x1a\x12.User.UserResponse\x12\x35\n\nDeleteUser\x12\x13.User.UserIdRequest\x1a\x12.User.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Protos.user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=27
  _globals['_USERREQUEST']._serialized_end=81
  _globals['_USERIDREQUEST']._serialized_start=83
  _globals['_USERIDREQUEST']._serialized_end=110
  _globals['_USERRESPONSE']._serialized_start=112
  _globals['_USERRESPONSE']._serialized_end=180
  _globals['_USERSERVICE']._serialized_start=183
  _globals['_USERSERVICE']._serialized_end=406
# @@protoc_insertion_point(module_scope)
